/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Category = IDL.Record({
  'id' : IDL.Nat,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'createdDate' : Time,
  'lastUpdatedDate' : Time,
});
export const StoreHours = IDL.Record({
  'tuesday' : IDL.Text,
  'wednesday' : IDL.Text,
  'saturday' : IDL.Text,
  'thursday' : IDL.Text,
  'sunday' : IDL.Text,
  'friday' : IDL.Text,
  'monday' : IDL.Text,
});
export const Coordinates = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const UserRoleInfo = IDL.Record({
  'principal' : IDL.Text,
  'role' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PaginatedCategories = IDL.Record({
  'categories' : IDL.Vec(Category),
  'hasMore' : IDL.Bool,
  'totalCount' : IDL.Nat,
});
export const Product = IDL.Record({
  'categoryId' : IDL.Nat,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'createdDate' : IDL.Opt(Time),
  'description' : IDL.Opt(IDL.Text),
  'isFeatured' : IDL.Bool,
  'barcode' : IDL.Text,
  'lastUpdatedDate' : IDL.Opt(Time),
  'photo' : IDL.Opt(ExternalBlob),
});
export const CategoryWithProducts = IDL.Record({
  'productCount' : IDL.Nat,
  'category' : Category,
  'products' : IDL.Vec(Product),
});
export const PaginatedProducts = IDL.Record({
  'totalCount' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'currentPage' : IDL.Nat,
  'totalPages' : IDL.Nat,
  'products' : IDL.Vec(Product),
});
export const StoreDetails = IDL.Record({
  'name' : IDL.Text,
  'banner' : IDL.Opt(ExternalBlob),
  'createdDate' : IDL.Opt(Time),
  'whatsapp' : IDL.Text,
  'storeHours' : StoreHours,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'lastUpdatedDate' : IDL.Opt(Time),
  'phone' : IDL.Text,
  'coordinates' : Coordinates,
});
export const ProductSearchCriteria = IDL.Record({
  'categoryId' : IDL.Opt(IDL.Nat),
  'featuredOnly' : IDL.Opt(IDL.Bool),
  'featuredFirst' : IDL.Opt(IDL.Bool),
  'searchValue' : IDL.Opt(IDL.Text),
  'searchBy' : IDL.Opt(IDL.Text),
});
export const ProductSearchResults = IDL.Record({
  'totalCount' : IDL.Nat,
  'totalPages' : IDL.Nat,
  'products' : IDL.Vec(Product),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Bool,
        IDL.Opt(ExternalBlob),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserRole' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'bulkImportCategories' : IDL.Func(
      [IDL.Vec(Category)],
      [
        IDL.Record({
          'imported' : IDL.Nat,
          'skipped' : IDL.Nat,
          'errors' : IDL.Vec(IDL.Text),
        }),
      ],
      [],
    ),
  'createStoreDetails' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        StoreHours,
        Coordinates,
      ],
      [],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllUserRoles' : IDL.Func([], [IDL.Vec(UserRoleInfo)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoriesPaginated' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [PaginatedCategories],
      ['query'],
    ),
  'getCategoriesWithProducts' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(CategoryWithProducts)],
      ['query'],
    ),
  'getCategoryById' : IDL.Func([IDL.Nat], [IDL.Opt(Category)], ['query']),
  'getCategoryProductsPaginated' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Bool)],
      [IDL.Record({ 'totalCount' : IDL.Nat, 'products' : IDL.Vec(Product) })],
      ['query'],
    ),
  'getFeaturedProducts' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Record({ 'totalCount' : IDL.Nat, 'products' : IDL.Vec(Product) })],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Bool),
        IDL.Opt(IDL.Bool),
      ],
      [PaginatedProducts],
      ['query'],
    ),
  'getProductsByCategory' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Bool)],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getStoreDetails' : IDL.Func([], [StoreDetails], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'importProducts' : IDL.Func([IDL.Vec(Product)], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeAdminRole' : IDL.Func([IDL.Text], [], []),
  'reorderCategory' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProducts' : IDL.Func(
      [ProductSearchCriteria],
      [ProductSearchResults],
      ['query'],
    ),
  'toggleCategoryActivation' : IDL.Func([IDL.Nat], [], []),
  'toggleStock' : IDL.Func([IDL.Text], [], []),
  'updateCategory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'updateCategoryId' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Bool,
        IDL.Opt(ExternalBlob),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateProductFeaturedStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateStoreDetails' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        StoreHours,
        Coordinates,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'createdDate' : Time,
    'lastUpdatedDate' : Time,
  });
  const StoreHours = IDL.Record({
    'tuesday' : IDL.Text,
    'wednesday' : IDL.Text,
    'saturday' : IDL.Text,
    'thursday' : IDL.Text,
    'sunday' : IDL.Text,
    'friday' : IDL.Text,
    'monday' : IDL.Text,
  });
  const Coordinates = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const UserRoleInfo = IDL.Record({
    'principal' : IDL.Text,
    'role' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PaginatedCategories = IDL.Record({
    'categories' : IDL.Vec(Category),
    'hasMore' : IDL.Bool,
    'totalCount' : IDL.Nat,
  });
  const Product = IDL.Record({
    'categoryId' : IDL.Nat,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'createdDate' : IDL.Opt(Time),
    'description' : IDL.Opt(IDL.Text),
    'isFeatured' : IDL.Bool,
    'barcode' : IDL.Text,
    'lastUpdatedDate' : IDL.Opt(Time),
    'photo' : IDL.Opt(ExternalBlob),
  });
  const CategoryWithProducts = IDL.Record({
    'productCount' : IDL.Nat,
    'category' : Category,
    'products' : IDL.Vec(Product),
  });
  const PaginatedProducts = IDL.Record({
    'totalCount' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'currentPage' : IDL.Nat,
    'totalPages' : IDL.Nat,
    'products' : IDL.Vec(Product),
  });
  const StoreDetails = IDL.Record({
    'name' : IDL.Text,
    'banner' : IDL.Opt(ExternalBlob),
    'createdDate' : IDL.Opt(Time),
    'whatsapp' : IDL.Text,
    'storeHours' : StoreHours,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'lastUpdatedDate' : IDL.Opt(Time),
    'phone' : IDL.Text,
    'coordinates' : Coordinates,
  });
  const ProductSearchCriteria = IDL.Record({
    'categoryId' : IDL.Opt(IDL.Nat),
    'featuredOnly' : IDL.Opt(IDL.Bool),
    'featuredFirst' : IDL.Opt(IDL.Bool),
    'searchValue' : IDL.Opt(IDL.Text),
    'searchBy' : IDL.Opt(IDL.Text),
  });
  const ProductSearchResults = IDL.Record({
    'totalCount' : IDL.Nat,
    'totalPages' : IDL.Nat,
    'products' : IDL.Vec(Product),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Bool,
          IDL.Opt(ExternalBlob),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserRole' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'bulkImportCategories' : IDL.Func(
        [IDL.Vec(Category)],
        [
          IDL.Record({
            'imported' : IDL.Nat,
            'skipped' : IDL.Nat,
            'errors' : IDL.Vec(IDL.Text),
          }),
        ],
        [],
      ),
    'createStoreDetails' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          StoreHours,
          Coordinates,
        ],
        [],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllUserRoles' : IDL.Func([], [IDL.Vec(UserRoleInfo)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoriesPaginated' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [PaginatedCategories],
        ['query'],
      ),
    'getCategoriesWithProducts' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(CategoryWithProducts)],
        ['query'],
      ),
    'getCategoryById' : IDL.Func([IDL.Nat], [IDL.Opt(Category)], ['query']),
    'getCategoryProductsPaginated' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Bool)],
        [IDL.Record({ 'totalCount' : IDL.Nat, 'products' : IDL.Vec(Product) })],
        ['query'],
      ),
    'getFeaturedProducts' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Record({ 'totalCount' : IDL.Nat, 'products' : IDL.Vec(Product) })],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Bool),
          IDL.Opt(IDL.Bool),
        ],
        [PaginatedProducts],
        ['query'],
      ),
    'getProductsByCategory' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Bool)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getStoreDetails' : IDL.Func([], [StoreDetails], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'importProducts' : IDL.Func([IDL.Vec(Product)], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeAdminRole' : IDL.Func([IDL.Text], [], []),
    'reorderCategory' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProducts' : IDL.Func(
        [ProductSearchCriteria],
        [ProductSearchResults],
        ['query'],
      ),
    'toggleCategoryActivation' : IDL.Func([IDL.Nat], [], []),
    'toggleStock' : IDL.Func([IDL.Text], [], []),
    'updateCategory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'updateCategoryId' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Bool,
          IDL.Opt(ExternalBlob),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateProductFeaturedStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateStoreDetails' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          StoreHours,
          Coordinates,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };