/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : bigint,
  'order' : bigint,
  'name' : string,
  'createdDate' : Time,
  'lastUpdatedDate' : Time,
}
export interface CategoryWithProducts {
  'productCount' : bigint,
  'category' : Category,
  'products' : Array<Product>,
}
export interface Coordinates { 'latitude' : number, 'longitude' : number }
export type ExternalBlob = Uint8Array;
export interface PaginatedCategories {
  'categories' : Array<Category>,
  'hasMore' : boolean,
  'totalCount' : bigint,
}
export interface PaginatedProducts {
  'totalCount' : bigint,
  'pageSize' : bigint,
  'currentPage' : bigint,
  'totalPages' : bigint,
  'products' : Array<Product>,
}
export interface Product {
  'categoryId' : bigint,
  'inStock' : boolean,
  'name' : string,
  'createdDate' : [] | [Time],
  'description' : [] | [string],
  'isFeatured' : boolean,
  'barcode' : string,
  'lastUpdatedDate' : [] | [Time],
  'photo' : [] | [ExternalBlob],
}
export interface ProductSearchCriteria {
  'categoryId' : [] | [bigint],
  'featuredOnly' : [] | [boolean],
  'featuredFirst' : [] | [boolean],
  'searchValue' : [] | [string],
  'searchBy' : [] | [string],
}
export interface ProductSearchResults {
  'totalCount' : bigint,
  'totalPages' : bigint,
  'products' : Array<Product>,
}
export interface StoreDetails {
  'name' : string,
  'banner' : [] | [ExternalBlob],
  'createdDate' : [] | [Time],
  'whatsapp' : string,
  'storeHours' : StoreHours,
  'email' : string,
  'address' : string,
  'lastUpdatedDate' : [] | [Time],
  'phone' : string,
  'coordinates' : Coordinates,
}
export interface StoreHours {
  'tuesday' : string,
  'wednesday' : string,
  'saturday' : string,
  'thursday' : string,
  'sunday' : string,
  'friday' : string,
  'monday' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserRoleInfo { 'principal' : string, 'role' : string }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[string, bigint], undefined>,
  'addProduct' : ActorMethod<
    [
      string,
      string,
      bigint,
      [] | [string],
      boolean,
      [] | [ExternalBlob],
      boolean,
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserRole' : ActorMethod<[string, string], undefined>,
  'bulkImportCategories' : ActorMethod<
    [Array<Category>],
    { 'imported' : bigint, 'skipped' : bigint, 'errors' : Array<string> }
  >,
  'createStoreDetails' : ActorMethod<
    [
      string,
      [] | [ExternalBlob],
      string,
      string,
      string,
      string,
      StoreHours,
      Coordinates,
    ],
    undefined
  >,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllUserRoles' : ActorMethod<[], Array<UserRoleInfo>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoriesPaginated' : ActorMethod<[bigint, bigint], PaginatedCategories>,
  'getCategoriesWithProducts' : ActorMethod<
    [bigint, bigint],
    Array<CategoryWithProducts>
  >,
  'getCategoryById' : ActorMethod<[bigint], [] | [Category]>,
  'getCategoryProductsPaginated' : ActorMethod<
    [bigint, bigint, bigint, [] | [boolean]],
    { 'totalCount' : bigint, 'products' : Array<Product> }
  >,
  'getFeaturedProducts' : ActorMethod<
    [bigint, bigint],
    { 'totalCount' : bigint, 'products' : Array<Product> }
  >,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getProducts' : ActorMethod<
    [bigint, bigint, string, [] | [bigint], [] | [boolean], [] | [boolean]],
    PaginatedProducts
  >,
  'getProductsByCategory' : ActorMethod<
    [bigint, [] | [boolean]],
    Array<Product>
  >,
  'getStoreDetails' : ActorMethod<[], StoreDetails>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'importProducts' : ActorMethod<[Array<Product>], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeAdminRole' : ActorMethod<[string], undefined>,
  'reorderCategory' : ActorMethod<[bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[ProductSearchCriteria], ProductSearchResults>,
  'toggleCategoryActivation' : ActorMethod<[bigint], undefined>,
  'toggleStock' : ActorMethod<[string], undefined>,
  'updateCategory' : ActorMethod<[bigint, string, bigint], undefined>,
  'updateCategoryId' : ActorMethod<[bigint, bigint], undefined>,
  'updateProduct' : ActorMethod<
    [
      string,
      string,
      bigint,
      [] | [string],
      boolean,
      [] | [ExternalBlob],
      boolean,
    ],
    undefined
  >,
  'updateProductFeaturedStatus' : ActorMethod<[string, boolean], undefined>,
  'updateStoreDetails' : ActorMethod<
    [
      string,
      [] | [ExternalBlob],
      string,
      string,
      string,
      string,
      StoreHours,
      Coordinates,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];