/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Category {
    id: bigint;
    order: bigint;
    name: string;
    createdDate: Time;
    lastUpdatedDate: Time;
}
export type Time = bigint;
export interface StoreHours {
    tuesday: string;
    wednesday: string;
    saturday: string;
    thursday: string;
    sunday: string;
    friday: string;
    monday: string;
}
export interface Coordinates {
    latitude: number;
    longitude: number;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PaginatedCategories {
    categories: Array<Category>;
    hasMore: boolean;
    totalCount: bigint;
}
export interface StoreDetails {
    name: string;
    banner?: ExternalBlob;
    createdDate?: Time;
    whatsapp: string;
    storeHours: StoreHours;
    email: string;
    address: string;
    lastUpdatedDate?: Time;
    phone: string;
    coordinates: Coordinates;
}
export interface ProductSearchCriteria {
    categoryId?: bigint;
    featuredOnly?: boolean;
    featuredFirst?: boolean;
    searchValue?: string;
    searchBy?: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CategoryWithProducts {
    productCount: bigint;
    category: Category;
    products: Array<Product>;
}
export interface UserRoleInfo {
    principal: string;
    role: string;
}
export interface PaginatedProducts {
    totalCount: bigint;
    pageSize: bigint;
    currentPage: bigint;
    totalPages: bigint;
    products: Array<Product>;
}
export interface ProductSearchResults {
    totalCount: bigint;
    totalPages: bigint;
    products: Array<Product>;
}
export interface Product {
    categoryId: bigint;
    inStock: boolean;
    name: string;
    createdDate?: Time;
    description?: string;
    isFeatured: boolean;
    barcode: string;
    lastUpdatedDate?: Time;
    photo?: ExternalBlob;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCategory(name: string, order: bigint): Promise<void>;
    addProduct(barcode: string, name: string, categoryId: bigint, description: string | null, inStock: boolean, photo: ExternalBlob | null, isFeatured: boolean): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignUserRole(principalText: string, roleText: string): Promise<void>;
    bulkImportCategories(categoriesToImport: Array<Category>): Promise<{
        imported: bigint;
        skipped: bigint;
        errors: Array<string>;
    }>;
    createStoreDetails(name: string, banner: ExternalBlob | null, address: string, phone: string, whatsapp: string, email: string, storeHours: StoreHours, coordinates: Coordinates): Promise<void>;
    deleteCategory(id: bigint): Promise<void>;
    deleteProduct(barcode: string): Promise<void>;
    getAllCategories(): Promise<Array<Category>>;
    getAllUserRoles(): Promise<Array<UserRoleInfo>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCategoriesPaginated(offset: bigint, limit: bigint): Promise<PaginatedCategories>;
    getCategoriesWithProducts(offset: bigint, limit: bigint): Promise<Array<CategoryWithProducts>>;
    getCategoryById(categoryId: bigint): Promise<Category | null>;
    getCategoryProductsPaginated(categoryId: bigint, offset: bigint, limit: bigint, featuredOnly: boolean | null): Promise<{
        totalCount: bigint;
        products: Array<Product>;
    }>;
    getFeaturedProducts(offset: bigint, limit: bigint): Promise<{
        totalCount: bigint;
        products: Array<Product>;
    }>;
    getProduct(barcode: string): Promise<Product | null>;
    getProducts(page: bigint, pageSize: bigint, search: string, categoryId: bigint | null, featuredOnly: boolean | null, featuredFirst: boolean | null): Promise<PaginatedProducts>;
    getProductsByCategory(categoryId: bigint, featuredOnly: boolean | null): Promise<Array<Product>>;
    getStoreDetails(): Promise<StoreDetails>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    importProducts(importedProducts: Array<Product>): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    removeAdminRole(principalText: string): Promise<void>;
    reorderCategory(id: bigint, newOrder: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchProducts(criteria: ProductSearchCriteria): Promise<ProductSearchResults>;
    toggleCategoryActivation(id: bigint): Promise<void>;
    toggleStock(barcode: string): Promise<void>;
    updateCategory(id: bigint, name: string, order: bigint): Promise<void>;
    updateCategoryId(oldCategoryId: bigint, newCategoryId: bigint): Promise<void>;
    updateProduct(barcode: string, name: string, categoryId: bigint, description: string | null, inStock: boolean, photo: ExternalBlob | null, isFeatured: boolean): Promise<void>;
    updateProductFeaturedStatus(barcode: string, isFeatured: boolean): Promise<void>;
    updateStoreDetails(name: string, banner: ExternalBlob | null, address: string, phone: string, whatsapp: string, email: string, storeHours: StoreHours, coordinates: Coordinates): Promise<void>;
}
import type { Category as _Category, CategoryWithProducts as _CategoryWithProducts, Coordinates as _Coordinates, ExternalBlob as _ExternalBlob, PaginatedProducts as _PaginatedProducts, Product as _Product, ProductSearchCriteria as _ProductSearchCriteria, ProductSearchResults as _ProductSearchResults, StoreDetails as _StoreDetails, StoreHours as _StoreHours, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCategory(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategory(arg0, arg1);
            return result;
        }
    }
    async addProduct(arg0: string, arg1: string, arg2: bigint, arg3: string | null, arg4: boolean, arg5: ExternalBlob | null, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), arg4, await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), arg4, await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignUserRole(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignUserRole(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignUserRole(arg0, arg1);
            return result;
        }
    }
    async bulkImportCategories(arg0: Array<Category>): Promise<{
        imported: bigint;
        skipped: bigint;
        errors: Array<string>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkImportCategories(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkImportCategories(arg0);
            return result;
        }
    }
    async createStoreDetails(arg0: string, arg1: ExternalBlob | null, arg2: string, arg3: string, arg4: string, arg5: string, arg6: StoreHours, arg7: Coordinates): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStoreDetails(arg0, await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStoreDetails(arg0, await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async deleteCategory(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getAllCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategories();
            return result;
        }
    }
    async getAllUserRoles(): Promise<Array<UserRoleInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserRoles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserRoles();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategoriesPaginated(arg0: bigint, arg1: bigint): Promise<PaginatedCategories> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoriesPaginated(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoriesPaginated(arg0, arg1);
            return result;
        }
    }
    async getCategoriesWithProducts(arg0: bigint, arg1: bigint): Promise<Array<CategoryWithProducts>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoriesWithProducts(arg0, arg1);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoriesWithProducts(arg0, arg1);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategoryById(arg0: bigint): Promise<Category | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryById(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryById(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategoryProductsPaginated(arg0: bigint, arg1: bigint, arg2: bigint, arg3: boolean | null): Promise<{
        totalCount: bigint;
        products: Array<Product>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryProductsPaginated(arg0, arg1, arg2, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg3));
                return from_candid_record_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryProductsPaginated(arg0, arg1, arg2, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg3));
            return from_candid_record_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedProducts(arg0: bigint, arg1: bigint): Promise<{
        totalCount: bigint;
        products: Array<Product>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedProducts(arg0, arg1);
                return from_candid_record_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedProducts(arg0, arg1);
            return from_candid_record_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: string): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(arg0: bigint, arg1: bigint, arg2: string, arg3: bigint | null, arg4: boolean | null, arg5: boolean | null): Promise<PaginatedProducts> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts(arg0, arg1, arg2, to_candid_opt_n30(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n27(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n27(this._uploadFile, this._downloadFile, arg5));
                return from_candid_PaginatedProducts_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts(arg0, arg1, arg2, to_candid_opt_n30(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n27(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n27(this._uploadFile, this._downloadFile, arg5));
            return from_candid_PaginatedProducts_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: bigint, arg1: boolean | null): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(arg0, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(arg0, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStoreDetails(): Promise<StoreDetails> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoreDetails();
                return from_candid_StoreDetails_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoreDetails();
            return from_candid_StoreDetails_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async importProducts(arg0: Array<Product>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importProducts(await to_candid_vec_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importProducts(await to_candid_vec_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeAdminRole(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAdminRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAdminRole(arg0);
            return result;
        }
    }
    async reorderCategory(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderCategory(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchProducts(arg0: ProductSearchCriteria): Promise<ProductSearchResults> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProducts(to_candid_ProductSearchCriteria_n38(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ProductSearchResults_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProducts(to_candid_ProductSearchCriteria_n38(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ProductSearchResults_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleCategoryActivation(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleCategoryActivation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleCategoryActivation(arg0);
            return result;
        }
    }
    async toggleStock(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleStock(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleStock(arg0);
            return result;
        }
    }
    async updateCategory(arg0: bigint, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0, arg1, arg2);
            return result;
        }
    }
    async updateCategoryId(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategoryId(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategoryId(arg0, arg1);
            return result;
        }
    }
    async updateProduct(arg0: string, arg1: string, arg2: bigint, arg3: string | null, arg4: boolean, arg5: ExternalBlob | null, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), arg4, await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), arg4, await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async updateProductFeaturedStatus(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProductFeaturedStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProductFeaturedStatus(arg0, arg1);
            return result;
        }
    }
    async updateStoreDetails(arg0: string, arg1: ExternalBlob | null, arg2: string, arg3: string, arg4: string, arg5: string, arg6: StoreHours, arg7: Coordinates): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStoreDetails(arg0, await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStoreDetails(arg0, await to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
}
async function from_candid_CategoryWithProducts_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CategoryWithProducts): Promise<CategoryWithProducts> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_PaginatedProducts_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedProducts): Promise<PaginatedProducts> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_ProductSearchResults_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductSearchResults): Promise<ProductSearchResults> {
    return await from_candid_record_n41(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_StoreDetails_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoreDetails): Promise<StoreDetails> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Category]): Category | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Promise<Product | null> {
    return value.length === 0 ? null : await from_candid_Product_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    productCount: bigint;
    category: _Category;
    products: Array<_Product>;
}): Promise<{
    productCount: bigint;
    category: Category;
    products: Array<Product>;
}> {
    return {
        productCount: value.productCount,
        category: value.category,
        products: await from_candid_vec_n19(_uploadFile, _downloadFile, value.products)
    };
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categoryId: bigint;
    inStock: boolean;
    name: string;
    createdDate: [] | [_Time];
    description: [] | [string];
    isFeatured: boolean;
    barcode: string;
    lastUpdatedDate: [] | [_Time];
    photo: [] | [_ExternalBlob];
}): Promise<{
    categoryId: bigint;
    inStock: boolean;
    name: string;
    createdDate?: Time;
    description?: string;
    isFeatured: boolean;
    barcode: string;
    lastUpdatedDate?: Time;
    photo?: ExternalBlob;
}> {
    return {
        categoryId: value.categoryId,
        inStock: value.inStock,
        name: value.name,
        createdDate: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.createdDate)),
        description: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.description)),
        isFeatured: value.isFeatured,
        barcode: value.barcode,
        lastUpdatedDate: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.lastUpdatedDate)),
        photo: record_opt_to_undefined(await from_candid_opt_n24(_uploadFile, _downloadFile, value.photo))
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalCount: bigint;
    products: Array<_Product>;
}): Promise<{
    totalCount: bigint;
    products: Array<Product>;
}> {
    return {
        totalCount: value.totalCount,
        products: await from_candid_vec_n19(_uploadFile, _downloadFile, value.products)
    };
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalCount: bigint;
    pageSize: bigint;
    currentPage: bigint;
    totalPages: bigint;
    products: Array<_Product>;
}): Promise<{
    totalCount: bigint;
    pageSize: bigint;
    currentPage: bigint;
    totalPages: bigint;
    products: Array<Product>;
}> {
    return {
        totalCount: value.totalCount,
        pageSize: value.pageSize,
        currentPage: value.currentPage,
        totalPages: value.totalPages,
        products: await from_candid_vec_n19(_uploadFile, _downloadFile, value.products)
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    banner: [] | [_ExternalBlob];
    createdDate: [] | [_Time];
    whatsapp: string;
    storeHours: _StoreHours;
    email: string;
    address: string;
    lastUpdatedDate: [] | [_Time];
    phone: string;
    coordinates: _Coordinates;
}): Promise<{
    name: string;
    banner?: ExternalBlob;
    createdDate?: Time;
    whatsapp: string;
    storeHours: StoreHours;
    email: string;
    address: string;
    lastUpdatedDate?: Time;
    phone: string;
    coordinates: Coordinates;
}> {
    return {
        name: value.name,
        banner: record_opt_to_undefined(await from_candid_opt_n24(_uploadFile, _downloadFile, value.banner)),
        createdDate: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.createdDate)),
        whatsapp: value.whatsapp,
        storeHours: value.storeHours,
        email: value.email,
        address: value.address,
        lastUpdatedDate: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.lastUpdatedDate)),
        phone: value.phone,
        coordinates: value.coordinates
    };
}
async function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalCount: bigint;
    totalPages: bigint;
    products: Array<_Product>;
}): Promise<{
    totalCount: bigint;
    totalPages: bigint;
    products: Array<Product>;
}> {
    return {
        totalCount: value.totalCount,
        totalPages: value.totalPages,
        products: await from_candid_vec_n19(_uploadFile, _downloadFile, value.products)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CategoryWithProducts>): Promise<Array<CategoryWithProducts>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CategoryWithProducts_n17(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n20(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ProductSearchCriteria_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductSearchCriteria): _ProductSearchCriteria {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
async function to_candid_Product_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): Promise<_Product> {
    return await to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categoryId: bigint;
    inStock: boolean;
    name: string;
    createdDate?: Time;
    description?: string;
    isFeatured: boolean;
    barcode: string;
    lastUpdatedDate?: Time;
    photo?: ExternalBlob;
}): Promise<{
    categoryId: bigint;
    inStock: boolean;
    name: string;
    createdDate: [] | [_Time];
    description: [] | [string];
    isFeatured: boolean;
    barcode: string;
    lastUpdatedDate: [] | [_Time];
    photo: [] | [_ExternalBlob];
}> {
    return {
        categoryId: value.categoryId,
        inStock: value.inStock,
        name: value.name,
        createdDate: value.createdDate ? candid_some(value.createdDate) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        isFeatured: value.isFeatured,
        barcode: value.barcode,
        lastUpdatedDate: value.lastUpdatedDate ? candid_some(value.lastUpdatedDate) : candid_none(),
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.photo)) : candid_none()
    };
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categoryId?: bigint;
    featuredOnly?: boolean;
    featuredFirst?: boolean;
    searchValue?: string;
    searchBy?: string;
}): {
    categoryId: [] | [bigint];
    featuredOnly: [] | [boolean];
    featuredFirst: [] | [boolean];
    searchValue: [] | [string];
    searchBy: [] | [string];
} {
    return {
        categoryId: value.categoryId ? candid_some(value.categoryId) : candid_none(),
        featuredOnly: value.featuredOnly ? candid_some(value.featuredOnly) : candid_none(),
        featuredFirst: value.featuredFirst ? candid_some(value.featuredFirst) : candid_none(),
        searchValue: value.searchValue ? candid_some(value.searchValue) : candid_none(),
        searchBy: value.searchBy ? candid_some(value.searchBy) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Product>): Promise<Array<_Product>> {
    return await Promise.all(value.map(async (x)=>await to_candid_Product_n36(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
